---
language: java
# skip the default install (mvn install -DskipTests=true) to speed up the build
install: true
script: mvn -q install -P examples
jdk:
- oraclejdk8
matrix:
  include:
  - jdk: oraclejdk7
    script: mvn -q deploy --settings .travis-settings.xml -Dno.gem.deploy=true -DdeployAtEnd=true
  - jdk: oraclejdk8
    script: mvn -q install -P java8
    after_success: mvn -q deploy -P java8 -pl java8 --settings .travis-settings.xml -DskipTests=true -Dmaven.javadoc.skip=true

# get us on the new container based builds, we're not using any fancyness
sudo: false

branches:
  only:
  - master
notifications:
  email:
  - 747902156@qq.com

